networks:
  laravel:
    driver: bridge

services:
  apachephp:
    build:
      context: .
      dockerfile: apachephp.dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel
    depends_on:
      - pgsql
  pgsql:
    image: postgres:14.3-alpine3.16
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: laravel
      POSTGRES_DB: laravel
    volumes:
      - ./pgsql:/var/lib/postgresql/data
    networks:
      - laravel
  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel
  npm:
    image: node:alpine
    volumes:
      - ./src:/var/www/html
    entrypoint: ['npm']
    working_dir: /var/www/html
    networks:
      - laravel
  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - pgsql
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel
  adminer:
    build:
      context: .
      dockerfile: adminer.dockerfile
    ports:
      - 8080:8080
    depends_on:
      - pgsql
      - apachephp
    networks:
      - laravel
